# Generated by Django 3.0.6 on 2020-06-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=200)),
                ('notice_date', models.DateTimeField(verbose_name='date published')),
                ('notice_count', models.IntegerField(default=0)),
                ('notice_text', models.TextField(blank=True)),
            ],
        ),
    ]
