# Generated by Django 3.0.6 on 2020-06-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='doc',
            field=models.FileField(upload_to='blog/files/'),
        ),
    ]
