# Generated by Django 3.0.6 on 2020-06-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200621_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='file',
            field=models.FileField(upload_to='photos/docs/'),
        ),
    ]
